CREATE TABLE IF NOT EXISTS saved_queries (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  database_uuid UUID NOT NULL,
  name VARCHAR(255) NOT NULL,
  query_state TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
